name: CI Pipeline

on:
  push:
    branches:
      - master 

env:
  MAVEN_OPTS: "-DskipTests=true" 

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/*.jar

      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=hananali0311_DevSecops_Pipeline -Dsonar.organization=hananali0311 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Run Tests
        run: mvn test



# name: CI Pipeline

# on:
#   push:
#     branches:
#       - master 
      
# env:
#   DOCKER_IMAGE: ankit1111/petapp:${{ github.sha }}
#   MAVEN_OPTS: "-DskipTests=true"      

# jobs:
#   build:
#     uses: ./.github/workflows/javabuild.yml
#     secrets: inherit

#   sonar:
#     uses: ./.github/workflows/sonar.yml
#     needs: build
#     secrets: inherit

#   test:
#     uses: ./.github/workflows/test.yml
#     needs: sonar
#     secrets: inherit







# # name: CI Pipeline
# # on:
# #   push:
# #     branches:
# #       - master 
      
# # env:
# #         DOCKER_IMAGE: ankit1111/petapp:${{ github.sha }}
# #         MAVEN_OPTS: "-DskipTests=true"      

# # jobs:
# #   build:
# #     uses: ./.github/workflows/javabuild.yml
# #     secrets: inherit
# #   sonar:
# #      uses: ./.github/workflows/sonar.yml
# #      needs: build
# #      secrets: inherit     

#   # test:
#   #   uses: ./.github/workflows/test.yml
#   #   needs: sonar
#   #   secrets: inherit  

# #   imagepush:
# #     uses: ./.github/workflows/imagepush.yml
# #     needs: test
# #     secrets: inherit  
