name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=hananali0311_DevSecops_Pipeline -Dsonar.organization=hananali0311 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}


# added






# # .github/workflows/sonar.yml
# name: Sonar Scan

# on:
#   workflow_call:

# jobs:
#   sonar:
#     runs-on: ubuntu-latest
#     steps:
#       - name: SonarCloud Scan
#         run: mvn sonar:sonar \
#           -Dsonar.projectKey=hananali0311_DevSecops_Pipeline \
#           -Dsonar.organization=hananali0311 \
#           -Dsonar.host.url=https://sonarcloud.io \
#           -Dsonar.login=${{ secrets.SONAR_TOKEN }}







# # .github/workflows/sonar.yml
# name: Sonar Scan

# on:
#  workflow_call:

# jobs:
#   sonar:
#     runs-on: ubuntu-latest
#     #needs: build  # Ensures Sonar runs after build succeeds
#     steps:
#       - name: SonarCloud Scan
#         run: mvn sonar:sonar -Dsonar.projectKey=ankit20000_DevSecops_Pipeline -Dsonar.organization=ankit20000 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3efd906389f89ff2f42493c5bda21481a0a75a68
